# Generated by Django 5.1.5 on 2025-08-19 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notice', models.JSONField(default=dict)),
                ('status', models.CharField(default='P', max_length=1)),
                ('handled_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.admin')),
                ('uploaded_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Noticeboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poster_name', models.CharField(default='', max_length=200)),
                ('poster_role', models.CharField(default='', max_length=20)),
                ('caption', models.TextField(default='')),
                ('attachments', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('R', 'Rejected'), ('A', 'Approved')], default='P', max_length=1)),
                ('posted_at', models.DateTimeField(default=None, null=True)),
                ('handled_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_noticeboard_posts', to='authorization.admin')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticeboard_posts', to='authorization.user')),
            ],
            options={
                'db_table': 'noticeboard',
            },
        ),
    ]
