from django.contrib import admin
from .models import User, Student, Instructor, Admin, Faculty, Department, Course, Degree, UniversityDetails, MailboxPost, Comment, Enrollment, EnrollmentCourse, Batch, Semester, BatchInstructor, Term, AssessmentScheme, Assessment, AssessmentResult, EmergencyContact, OTP, LoginAttempt, SISForm, Document, BatchInstructorDocument

# Register your models here.
admin.site.register(User)
admin.site.register(Student)
admin.site.register(Instructor)
admin.site.register(Admin)
admin.site.register(Faculty)
admin.site.register(Department)
admin.site.register(Course)
admin.site.register(Degree)
admin.site.register(UniversityDetails)
admin.site.register(MailboxPost)
admin.site.register(Comment)
admin.site.register(Enrollment)
admin.site.register(EnrollmentCourse)
admin.site.register(Term)
admin.site.register(Semester)
admin.site.register(Batch)
admin.site.register(BatchInstructor)
admin.site.register(SISForm)
admin.site.register(AssessmentScheme)
admin.site.register(Assessment)
admin.site.register(AssessmentResult)
admin.site.register(EmergencyContact)
admin.site.register(LoginAttempt)
admin.site.register(OTP)
admin.site.register(Document)
admin.site.register(BatchInstructorDocument)