# Generated by Django 5.1.1 on 2025-06-11 16:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0013_user_city_user_phone_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, default='', max_length=254, unique=True)),
                ('full_name', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='', max_length=100)),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('telegram_username', models.CharField(default='', max_length=50)),
                ('outlook_email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('profile_picture', models.ImageField(default='default_profile.png', upload_to='profile_pictures/')),
                ('password_last_changed_at', models.DateTimeField(auto_now_add=True)),
                ('password_reset_token', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_dean', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(default=None, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='custom_user_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheme', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_code', models.CharField(default='', max_length=20, unique=True)),
                ('course_name', models.CharField(default='', max_length=100)),
                ('is_elective', models.BooleanField(default=False)),
                ('is_supportive', models.BooleanField(default=False)),
                ('credit_hours', models.PositiveIntegerField(default=3)),
                ('description', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('office_location', models.CharField(default='', max_length=100)),
                ('contact_email', models.EmailField(default='', max_length=254)),
                ('contact_phone', models.CharField(default='', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', models.CharField(default='', max_length=20)),
                ('relation_to_user', models.CharField(default='', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('contact_email', models.EmailField(default='', max_length=254)),
                ('contact_phone', models.CharField(default='', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField(default=2025)),
                ('term_name', models.CharField(default='', max_length=100)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('result_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UniversityDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authorization.user')),
                ('degree', models.CharField(default='', max_length=100)),
                ('position_in_university', models.CharField(default='', max_length=100)),
                ('office_location', models.CharField(default='', max_length=100)),
                ('admin_level', models.CharField(choices=[('R', 'Root'), ('S', 'Senior'), ('J', 'Junior'), ('V', 'Viewer')], default='V', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authorization.user')),
                ('student_number', models.CharField(default='', max_length=20, unique=True)),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('U', 'Unapproved'), ('A', 'Active'), ('G', 'Graduated'), ('S', 'Suspended'), ('D', 'Dropped')], default='A', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_type', models.TextField(choices=[('Q', 'Quiz'), ('A', 'Assignment'), ('M', 'Midterm'), ('F', 'Final'), ('P', 'Project'), ('L', 'Lab Test'), ('V', 'Practical'), ('H', 'Thesis'), ('B', 'Lab Project'), ('J', 'Lab Assessment')], max_length=1)),
                ('assessment', models.JSONField(default=dict)),
                ('assigned_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(default=django.utils.timezone.now)),
                ('assessment_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.assessmentscheme')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(default='', max_length=50)),
                ('target_table', models.CharField(default='', max_length=50)),
                ('target_id', models.PositiveIntegerField(default=0)),
                ('action_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(default='0.0.0.0')),
                ('description', models.TextField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BatchInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_date', models.DateField(default=django.utils.timezone.now)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='assessmentscheme',
            name='batch_instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.batchinstructor'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.department'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('file_link', models.URLField(default='')),
                ('access_status', models.CharField(choices=[('A', 'Public'), ('B', 'Private'), ('C', 'Protected')], default='A', max_length=1)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authorization.emergencycontact'),
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.faculty'),
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('semester_count', models.PositiveIntegerField(default=8)),
                ('description', models.TextField(default='')),
                ('total_credits', models.PositiveIntegerField(default=120)),
                ('degree_type', models.CharField(choices=[('B', 'Bachelors'), ('M', 'Masters'), ('P', 'PhD')], default='B', max_length=1)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.faculty')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(default='0.0.0.0')),
                ('attempt_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('success', models.BooleanField(default=False)),
                ('user_agent', models.TextField(default='')),
                ('location_info', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MailboxAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointed_date', models.DateField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_admins', to='authorization.mailboxadmin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MailboxPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.JSONField(default=None)),
                ('approved_at', models.DateTimeField(default=None, null=True)),
                ('reactions', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected'), ('D', 'Disqualified')], default='P', max_length=1)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authorization.mailboxadmin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(default='')),
                ('reactions', models.JSONField(default=dict)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.user')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='authorization.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.mailboxpost')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('S', 'Student Quiz'), ('A', 'Student Assessment'), ('M', 'Student Mailbox')], default=None, max_length=1)),
                ('notification', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seen', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.user')),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(default='', max_length=254)),
                ('otp_code', models.CharField(default='', max_length=100)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_password_hash', models.CharField(default='', max_length=100)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('semester_name', models.CharField(default='', max_length=100)),
                ('duration', models.SmallIntegerField(default=16)),
                ('syllabus_structure', models.JSONField(default=dict)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.degree')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.semester'),
        ),
        migrations.AddField(
            model_name='batch',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.term'),
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_token', models.CharField(default='', max_length=100)),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('logout_time', models.DateTimeField(default=None, null=True)),
                ('ip_address', models.GenericIPAddressField(default='0.0.0.0')),
                ('user_agent', models.TextField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoConference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting_name', models.CharField(default='', max_length=100)),
                ('meeting_code', models.CharField(default='', max_length=50, unique=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('attendees', models.JSONField(default=list)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authorization.user')),
                ('degree', models.CharField(default='', max_length=100)),
                ('position_in_university', models.CharField(default='', max_length=100)),
                ('is_hod', models.BooleanField(default=False)),
                ('is_hof', models.BooleanField(default=False)),
                ('joined_date', models.DateField(default=django.utils.timezone.now)),
                ('specialization', models.CharField(default='', max_length=100)),
                ('employment_status', models.CharField(choices=[('U', 'Unapproved'), ('T', 'Transferred'), ('A', 'Active'), ('L', 'OnLeave'), ('R', 'Retired')], default='U', max_length=1)),
                ('department', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='batchinstructor',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.instructor'),
        ),
        migrations.CreateModel(
            name='SISForm',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authorization.student')),
                ('blood_group', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('O', 'O'), ('X', 'AB')], default='A', max_length=1)),
                ('ethnicity', models.TextField(default='Burmese', max_length=30)),
                ('religion', models.TextField(default='Buddhist', max_length=30)),
                ('NRC', models.TextField(default='9/MKN(N)191305', max_length=20)),
                ('birthplace', models.TextField(default='Yangon', max_length=30)),
                ('father_name', models.TextField(default='U Ba', max_length=40)),
                ('father_NRC', models.TextField(default='9/MKN(N)191305', max_length=20)),
                ('father_birthplace', models.TextField(default='Yangon', max_length=30)),
                ('father_city', models.TextField(default='Yangon', max_length=30)),
                ('father_phone', models.TextField(default='0', max_length=18)),
                ('father_profession', models.TextField(default='Businessman', max_length=20)),
                ('father_gmail', models.EmailField(default='uba@gmail.com', max_length=50)),
                ('father_ethnicity', models.TextField(default='Burmese', max_length=30)),
                ('father_religion', models.TextField(default='Buddhist', max_length=30)),
                ('mother_name', models.TextField(default='Daw Hla', max_length=40)),
                ('mother_NRC', models.TextField(default='9/MKN(N)191305', max_length=20)),
                ('mother_birthplace', models.TextField(default='Yangon', max_length=30)),
                ('mother_city', models.TextField(default='Yangon', max_length=30)),
                ('mother_phone', models.TextField(default='0', max_length=18)),
                ('mother_profession', models.TextField(default='Businessman', max_length=20)),
                ('mother_gmail', models.EmailField(default='dawhla@gmail.com', max_length=50)),
                ('mother_ethnicity', models.TextField(default='Burmese', max_length=30)),
                ('mother_religion', models.TextField(default='Buddhist', max_length=30)),
                ('matric_roll_no', models.TextField(default='မမ-၉၂၉', max_length=10)),
                ('exam_dept', models.TextField(default='ထ(၃)၊ပြင်ဦးလွင်', max_length=60)),
                ('passed_year', models.PositiveSmallIntegerField(default=2022)),
                ('total_marks', models.PositiveSmallIntegerField(default=516)),
                ('has_spouse', models.BooleanField(default=False)),
                ('spouse_name', models.TextField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result', models.JSONField(default=dict)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.batch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='student',
            name='degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.degree'),
        ),
        migrations.CreateModel(
            name='MailboxReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='authorization.mailboxpost')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to='authorization.student')),
            ],
        ),
        migrations.AddField(
            model_name='mailboxpost',
            name='uploaded_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authorization.student'),
        ),
        migrations.AddField(
            model_name='mailboxadmin',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.student'),
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer', models.JSONField(default=dict)),
                ('mark', models.PositiveIntegerField(default=0)),
                ('graded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.assessment')),
                ('graded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.instructor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authorization.studentbatch')),
                ('enrollment_form', models.JSONField(default=dict)),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now)),
                ('handled_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authorization.admin')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
