# Generated by Django 5.1.1 on 2025-04-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('U', 'Unapproved'), ('A', 'Active'), ('G', 'Graduated'), ('S', 'Suspended'), ('D', 'Dropped')], default='A', max_length=1),
        ),
    ]
