# Generated by Django 5.1.1 on 2025-07-04 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='faculty',
        ),
        migrations.AddField(
            model_name='faculty',
            name='faculty_photo',
            field=models.ImageField(default='default_profile.png', upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='head_of_faculty',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.user'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='location',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
