# Generated by Django 5.1.1 on 2025-07-05 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_remove_department_faculty_faculty_faculty_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='department',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='department',
            name='description',
        ),
        migrations.RemoveField(
            model_name='department',
            name='name',
        ),
        migrations.RemoveField(
            model_name='department',
            name='office_location',
        ),
    ]
