# Generated by Django 5.1.1 on 2025-04-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_alter_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentscheme',
            name='assessment_type',
            field=models.CharField(choices=[('Q', 'Quiz'), ('A', 'Assignment'), ('M', 'Midterm'), ('F', 'Final'), ('P', 'Project'), ('L', 'Lab Test'), ('V', 'Practical'), ('H', 'Thesis'), ('B', 'Lab Project'), ('J', 'Lab Assessment')], default='Q', max_length=1),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='employment_status',
            field=models.CharField(choices=[('U', 'Unapproved'), ('T', 'Transferred'), ('A', 'Active'), ('L', 'OnLeave'), ('R', 'Retired')], default='A', max_length=1),
        ),
    ]
