# Generated by Django 5.1.1 on 2025-07-18 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_alter_term_end_date_alter_term_result_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchinstructor',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.instructor'),
        ),
    ]
