# Generated by Django 5.1.1 on 2025-07-05 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_remove_department_contact_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
