# Generated by Django 5.1.1 on 2025-07-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_alter_batchinstructor_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchinstructor',
            name='room_data',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
