# Generated by Django 5.1.1 on 2025-07-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_batchinstructor_room_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='is_hod',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='is_hof',
        ),
        migrations.AlterField(
            model_name='instructor',
            name='employment_status',
            field=models.CharField(choices=[('U', 'Unapproved'), ('T', 'Transferred'), ('R', 'Rejected'), ('A', 'Active'), ('L', 'OnLeave'), ('E', 'Retired')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('U', 'Unapproved'), ('R', 'Rejected'), ('A', 'Active'), ('G', 'Graduated'), ('S', 'Suspended'), ('D', 'Dropped')], default='A', max_length=1),
        ),
    ]
