# Generated by Django 5.1.1 on 2025-07-05 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_remove_course_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('office_location', models.CharField(default='', max_length=100)),
                ('contact_email', models.EmailField(default='', max_length=254)),
                ('contact_phone', models.CharField(default='', max_length=20)),
                ('department_photo', models.ImageField(default='default.jpg', upload_to='departments/')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.faculty')),
                ('head_of_department', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authorization.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='department',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.department'),
        ),
    ]
