# Generated by Django 5.1.1 on 2025-04-16 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.degree'),
        ),
    ]
