# Generated by Django 5.1.1 on 2025-07-05 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_department_course_department_instructor_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='office_location',
            new_name='location',
        ),
    ]
