# Generated by Django 5.1.1 on 2025-07-23 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_remove_instructor_is_hod_remove_instructor_is_hof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='assessment_type',
            field=models.TextField(choices=[('Q', 'Quiz'), ('A', 'Assignment'), ('M', 'Midterm'), ('F', 'Final'), ('P', 'Project'), ('L', 'Lab Test'), ('V', 'Practical'), ('H', 'Thesis'), ('B', 'Lab Project'), ('J', 'Lab Assessment'), ('C', 'Class Participation')], max_length=1),
        ),
        migrations.AlterField(
            model_name='assessmentscheme',
            name='batch_instructor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authorization.batchinstructor'),
        ),
        migrations.AlterField(
            model_name='batchinstructor',
            name='room_data',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='BatchInstructorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.batchinstructor')),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.document')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
