# Generated by Django 5.1.1 on 2025-04-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0006_alter_student_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_dean',
            field=models.BooleanField(default=False),
        ),
    ]
