# Generated by Django 5.1.1 on 2025-07-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0006_rename_office_location_department_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='credit_hours',
        ),
        migrations.AddField(
            model_name='course',
            name='course_credits',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='course',
            name='course_hours',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
