# Generated by Django 5.1.1 on 2025-07-05 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0007_remove_course_credit_hours_course_course_credits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_elective',
        ),
    ]
