# Generated by Django 5.1.1 on 2025-07-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0007_document_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='assigned_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='due_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
