# Generated by Django 5.1.1 on 2025-04-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0007_user_is_dean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='employment_status',
            field=models.CharField(choices=[('U', 'Unapproved'), ('T', 'Transferred'), ('A', 'Active'), ('L', 'OnLeave'), ('R', 'Retired')], default='U', max_length=1),
        ),
    ]
