# Generated by Django 5.1.1 on 2025-07-05 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0008_remove_course_is_elective'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_supportive',
        ),
    ]
