# Generated by Django 5.1.1 on 2025-07-24 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0008_alter_assessment_assigned_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentbatch',
            name='batch',
        ),
        migrations.AddField(
            model_name='studentbatch',
            name='batch_instructor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.batchinstructor'),
        ),
    ]
