# Generated by Django 5.1.1 on 2025-07-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0009_remove_studentbatch_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='due_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
