# Generated by Django 5.1.1 on 2025-05-09 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0009_alter_instructor_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailboxpost',
            name='uploaded_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authorization.student'),
        ),
    ]
