# Generated by Django 5.1.1 on 2025-07-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0009_remove_course_is_supportive'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='semester',
            name='courses',
            field=models.JSONField(default={}),
        ),
    ]
