# Generated by Django 5.1.1 on 2025-07-26 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0010_alter_assessment_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentresult',
            name='graded_at',
        ),
        migrations.RemoveField(
            model_name='assessmentresult',
            name='graded_by',
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.student'),
        ),
    ]
