# Generated by Django 5.1.1 on 2025-07-06 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0010_degree_code_semester_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='courses',
        ),
    ]
