# Generated by Django 5.1.1 on 2025-07-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0011_remove_semester_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='duration',
            field=models.PositiveSmallIntegerField(default=16),
        ),
    ]
