# Generated by Django 5.1.1 on 2025-05-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0011_mailboxreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailboxpost',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected'), ('D', 'Disqualified')], default='P', max_length=1),
        ),
    ]
