# Generated by Django 5.1.1 on 2025-07-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0011_remove_assessmentresult_graded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='roll_no',
            field=models.TextField(blank=True),
        ),
    ]
