# Generated by Django 5.1.1 on 2025-07-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0012_alter_semester_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='duration',
        ),
        migrations.AddField(
            model_name='semester',
            name='duration_weeks',
            field=models.PositiveSmallIntegerField(default=4),
        ),
    ]
