# Generated by Django 5.1.1 on 2025-07-31 08:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0012_student_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbatch',
            name='enrollment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='studentbatch',
            name='enrollment_form',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='studentbatch',
            name='handled_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authorization.admin'),
        ),
        migrations.AlterField(
            model_name='sisform',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('O', 'O'), ('X', 'AB')], default=None, max_length=1, null=True),
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
