# Generated by Django 5.1.1 on 2025-07-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0013_remove_semester_duration_semester_duration_weeks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degree',
            name='semester_count',
        ),
        migrations.AddField(
            model_name='degree',
            name='duration',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
