# Generated by Django 5.1.1 on 2025-05-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0013_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailboxpost',
            name='post',
            field=models.JSONField(default=None),
        ),
    ]
