# Generated by Django 5.1.1 on 2025-07-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0014_remove_degree_semester_count_degree_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='degree_image',
            field=models.ImageField(default='default.jpg', upload_to='degrees/'),
        ),
        migrations.AddField(
            model_name='degree',
            name='total_courses',
            field=models.PositiveIntegerField(default=48),
        ),
        migrations.AddField(
            model_name='degree',
            name='total_hours',
            field=models.PositiveBigIntegerField(default=260),
        ),
    ]
