# Generated by Django 5.1.1 on 2025-06-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0014_alter_mailboxpost_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
