# Generated by Django 5.1.1 on 2025-07-31 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0014_enrollment_enrollmentcourse_delete_studentbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='selected_subjects',
            field=models.JSONField(default=dict),
        ),
    ]
