# Generated by Django 5.1.1 on 2025-08-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0015_enrollment_selected_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
