# Generated by Django 5.1.1 on 2025-06-03 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0015_universitydetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mailboxpost',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
