# Generated by Django 5.1.1 on 2025-08-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0016_enrollment_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='handled_by',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='enrollment_status',
            field=models.CharField(choices=[('A', 'Approved'), ('P', 'Pending'), ('R', 'Rejected')], default='P', max_length=1),
        ),
    ]
