# Generated by Django 5.1.1 on 2025-08-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0017_remove_enrollment_handled_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='office_location',
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_level',
            field=models.CharField(choices=[('R', 'Read'), ('W', 'Write')], default='R', max_length=1),
        ),
    ]
