# Generated by Django 5.1.1 on 2025-08-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0018_remove_admin_office_location_alter_admin_admin_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='marking_scheme',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('S', 'Student'), ('E', 'Executive'), ('I', 'Instructor'), ('M', 'Student Mailbox')], default=None, max_length=1),
        ),
    ]
