# Generated by Django 5.1.1 on 2025-08-17 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0019_course_marking_scheme_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='assessment_scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.assessmentscheme'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='assessment_type',
            field=models.TextField(choices=[('Q', 'Quiz'), ('A', 'Assignment'), ('M', 'Midterm'), ('F', 'Final(Lab)'), ('D', 'Final(On Paper)'), ('P', 'Project'), ('L', 'Lab Test'), ('V', 'Practical'), ('H', 'Thesis'), ('B', 'Lab Project'), ('J', 'Lab Assessment'), ('C', 'Class Participation'), ('Z', 'Tutorial')], default='Q', max_length=1),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='assigned_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='due_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
